name: ganvis
dependencies: 
    - python=3.7
    - pytorch=1.7.1
    - torchvision
    - requests
    - numpy
    - librosa
    - ffmpeg
    - pip
    - pip:
          - youtube_dl
channels:
    - conda-forge
    - pytorch
